
/**
 * Data Export Utilities
 * Export query results to various formats (CSV, JSON, PDF)
 */

export interface ExportOptions {
  format: 'csv' | 'json' | 'pdf'
  filename: string
  data: any[]
  title?: string
  summary?: string
}

/**
 * Export data to CSV format
 */
export function exportToCSV(data: any[], filename: string): void {
  if (!data || data.length === 0) {
    throw new Error('No data to export')
  }

  const headers = Object.keys(data[0])
  const csvContent = [
    headers.join(','),
    ...data.map(row => 
      headers.map(header => {
        const value = row[header]
        // Escape quotes and wrap in quotes if contains comma or newline
        const stringValue = String(value || '')
        if (stringValue.includes(',') || stringValue.includes('\n') || stringValue.includes('"')) {
          return `"${stringValue.replace(/"/g, '""')}"`
        }
        return stringValue
      }).join(',')
    )
  ].join('\n')

  downloadFile(csvContent, filename, 'text/csv')
}

/**
 * Export data to JSON format
 */
export function exportToJSON(data: any[], filename: string, metadata?: any): void {
  if (!data || data.length === 0) {
    throw new Error('No data to export')
  }

  const exportData = {
    exportDate: new Date().toISOString(),
    recordCount: data.length,
    ...metadata,
    data
  }

  const jsonContent = JSON.stringify(exportData, null, 2)
  downloadFile(jsonContent, filename, 'application/json')
}

/**
 * Export data to PDF format (client-side)
 */
export async function exportToPDF(data: any[], filename: string, options?: {
  title?: string
  summary?: string
}): Promise<void> {
  // For PDF generation, we'll create a simple HTML document and use the browser's print functionality
  // In a production app, you might want to use a library like jsPDF or pdfmake
  
  const title = options?.title || 'Data Export'
  const summary = options?.summary || ''
  
  const headers = Object.keys(data[0])
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 20px;
        }
        h1 {
          color: #333;
          border-bottom: 2px solid #4F46E5;
          padding-bottom: 10px;
        }
        .summary {
          background: #f5f5f5;
          padding: 15px;
          border-radius: 5px;
          margin: 20px 0;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th {
          background: #4F46E5;
          color: white;
          padding: 12px;
          text-align: left;
          font-weight: bold;
        }
        td {
          padding: 10px;
          border-bottom: 1px solid #ddd;
        }
        tr:hover {
          background: #f9f9f9;
        }
        .metadata {
          margin-top: 20px;
          font-size: 12px;
          color: #666;
        }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      ${summary ? `<div class="summary">${summary}</div>` : ''}
      <table>
        <thead>
          <tr>
            ${headers.map(h => `<th>${h.replace(/_/g, ' ').toUpperCase()}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${data.map(row => `
            <tr>
              ${headers.map(h => `<td>${row[h] !== null && row[h] !== undefined ? row[h] : ''}</td>`).join('')}
            </tr>
          `).join('')}
        </tbody>
      </table>
      <div class="metadata">
        <p><strong>Export Date:</strong> ${new Date().toLocaleString()}</p>
        <p><strong>Record Count:</strong> ${data.length}</p>
        <p><strong>Generated by Picard.ai</strong></p>
      </div>
    </body>
    </html>
  `

  // Create a new window and print
  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(htmlContent)
    printWindow.document.close()
    
    // Wait for content to load before printing
    printWindow.onload = () => {
      printWindow.print()
      // Close window after printing (optional)
      setTimeout(() => printWindow.close(), 100)
    }
  }
}

/**
 * Helper function to download file
 */
function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
