import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🏢 Adding companies to Sales Database...')

  const companies = [
    {
      companyName: 'TechCorp Solutions',
      industry: 'Technology',
      contactName: 'James Anderson',
      email: 'james@techcorp.com',
      phone: '555-1001',
      address: '100 Tech Plaza',
      city: 'San Francisco',
      state: 'CA',
      country: 'USA',
      zipCode: '94105',
      website: 'https://techcorp.com',
      employeeCount: 500,
      annualRevenue: 15000000,
      lifetimeValue: 850000,
      contractValue: 250000,
      dateJoined: new Date('2022-01-15'),
      status: 'Active',
      tier: 'Enterprise',
    },
    {
      companyName: 'Global Finance Group',
      industry: 'Financial Services',
      contactName: 'Maria Rodriguez',
      email: 'maria@globalfinance.com',
      phone: '555-1002',
      address: '250 Wall Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      zipCode: '10005',
      website: 'https://globalfinance.com',
      employeeCount: 1200,
      annualRevenue: 45000000,
      lifetimeValue: 1250000,
      contractValue: 400000,
      dateJoined: new Date('2021-06-20'),
      status: 'Active',
      tier: 'Enterprise',
    },
    {
      companyName: 'Healthcare Innovations LLC',
      industry: 'Healthcare',
      contactName: 'Dr. Sarah Chen',
      email: 'sarah@healthinnovations.com',
      phone: '555-1003',
      address: '450 Medical Center Dr',
      city: 'Boston',
      state: 'MA',
      country: 'USA',
      zipCode: '02115',
      website: 'https://healthinnovations.com',
      employeeCount: 300,
      annualRevenue: 8000000,
      lifetimeValue: 620000,
      contractValue: 180000,
      dateJoined: new Date('2022-08-10'),
      status: 'Active',
      tier: 'Professional',
    },
    {
      companyName: 'Retail Dynamics Inc',
      industry: 'Retail',
      contactName: 'Michael Thompson',
      email: 'michael@retaildynamics.com',
      phone: '555-1004',
      address: '800 Commerce Blvd',
      city: 'Dallas',
      state: 'TX',
      country: 'USA',
      zipCode: '75201',
      website: 'https://retaildynamics.com',
      employeeCount: 2500,
      annualRevenue: 120000000,
      lifetimeValue: 475000,
      contractValue: 150000,
      dateJoined: new Date('2023-02-01'),
      status: 'Active',
      tier: 'Professional',
    },
    {
      companyName: 'EduTech Partners',
      industry: 'Education',
      contactName: 'Jennifer Lee',
      email: 'jennifer@edutechpartners.com',
      phone: '555-1005',
      address: '100 University Ave',
      city: 'Seattle',
      state: 'WA',
      country: 'USA',
      zipCode: '98101',
      website: 'https://edutechpartners.com',
      employeeCount: 150,
      annualRevenue: 5000000,
      lifetimeValue: 285000,
      contractValue: 85000,
      dateJoined: new Date('2023-03-15'),
      status: 'Active',
      tier: 'Standard',
    },
    {
      companyName: 'Manufacturing Pro Co',
      industry: 'Manufacturing',
      contactName: 'Robert Davis',
      email: 'robert@manufacturingpro.com',
      phone: '555-1006',
      address: '500 Industrial Park Rd',
      city: 'Detroit',
      state: 'MI',
      country: 'USA',
      zipCode: '48201',
      website: 'https://manufacturingpro.com',
      employeeCount: 800,
      annualRevenue: 35000000,
      lifetimeValue: 920000,
      contractValue: 310000,
      dateJoined: new Date('2021-11-05'),
      status: 'Active',
      tier: 'Enterprise',
    },
    {
      companyName: 'Green Energy Solutions',
      industry: 'Energy',
      contactName: 'Amanda Green',
      email: 'amanda@greenenergy.com',
      phone: '555-1007',
      address: '350 Renewable Way',
      city: 'Denver',
      state: 'CO',
      country: 'USA',
      zipCode: '80202',
      website: 'https://greenenergy.com',
      employeeCount: 250,
      annualRevenue: 12000000,
      lifetimeValue: 380000,
      contractValue: 120000,
      dateJoined: new Date('2022-04-20'),
      status: 'Active',
      tier: 'Professional',
    },
    {
      companyName: 'Legal Associates Group',
      industry: 'Legal Services',
      contactName: 'David Morrison',
      email: 'david@legalassociates.com',
      phone: '555-1008',
      address: '200 Law Center Plaza',
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      zipCode: '60601',
      website: 'https://legalassociates.com',
      employeeCount: 75,
      annualRevenue: 6000000,
      lifetimeValue: 195000,
      contractValue: 65000,
      dateJoined: new Date('2023-01-10'),
      status: 'Active',
      tier: 'Standard',
    },
    {
      companyName: 'CloudNet Systems',
      industry: 'Cloud Services',
      contactName: 'Lisa Wang',
      email: 'lisa@cloudnetsystems.com',
      phone: '555-1009',
      address: '700 Data Center Dr',
      city: 'Austin',
      state: 'TX',
      country: 'USA',
      zipCode: '78701',
      website: 'https://cloudnetsystems.com',
      employeeCount: 400,
      annualRevenue: 22000000,
      lifetimeValue: 740000,
      contractValue: 220000,
      dateJoined: new Date('2022-07-15'),
      status: 'Active',
      tier: 'Enterprise',
    },
    {
      companyName: 'FoodService Distributors',
      industry: 'Food & Beverage',
      contactName: 'Carlos Martinez',
      email: 'carlos@foodservice.com',
      phone: '555-1010',
      address: '400 Distribution Center',
      city: 'Miami',
      state: 'FL',
      country: 'USA',
      zipCode: '33101',
      website: 'https://foodservice.com',
      employeeCount: 600,
      annualRevenue: 28000000,
      lifetimeValue: 310000,
      contractValue: 95000,
      dateJoined: new Date('2023-05-01'),
      status: 'Active',
      tier: 'Professional',
    },
  ]

  for (const company of companies) {
    try {
      await prisma.salesCompany.upsert({
        where: { email: company.email },
        update: company,
        create: company,
      })
      console.log(`✅ Added ${company.companyName}`)
    } catch (error) {
      console.log(`⚠️  Skipped ${company.companyName} (might already exist)`)
    }
  }

  console.log('🎉 Companies added successfully!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
